# Generated by Django 4.2.10 on 2024-02-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
